### ISSUE TITLE
Issue on burning NFTs in devnet

### ISSUE THREAD

**Issue by irzinfante** [cryptoloutre/solana-tools#6]
Hello, I'm facing some issues when trying to use the most recent code of the repository for burning NFTs in devnet.

When I use the solana-tools page for devnet (https://solanatools-devnet.vercel.app/gallery) for burning NFTs everything works fine, and the instructions in the transaction for burning the NFT are like these:
![image](https://github.com/cryptoloutre/solana-tools/assets/16447836/1b526efe-f43c-4acf-9503-97a5e1e826a0)

However, when trying to do the same thing with a local instance (http://localhost:3001/burnNFT) of the solana-tool (doing the instalation following the [README.md](https://github.com/cryptoloutre/solana-tools#getting-started) and choosing the endpoint for devnet in the [_app.tsx](https://github.com/cryptoloutre/solana-tools/blob/main/src/pages/_app.tsx#L11) file) I can't burn the NFTs and the instructions of the transaction are these ones:
![image](https://github.com/cryptoloutre/solana-tools/assets/16447836/42578181-4cb2-4cec-bb24-052e1b6f1dc4)

I have also notice that at some point the name of the page for burning NFTs was changed: https://github.com/cryptoloutre/solana-tools/commit/d663760892c61db4a0d9ccf370f876aef0924e76. And it looks like the page in https://solanatools-devnet.vercel.app/ uses the old name, so I guess that the version of the code deployed there may not be the most recent code of the repository.

Could any clarification regarding all these things be given please? The code running in https://solanatools-devnet.vercel.app/ is working, and I would like to know which commit was it.

Many thanks in advance,
Iker

**Comment by irzinfante** [comment]
Understood. Thank you for your help and clarifications. :+1: 

From my side this issue can be closed. But if you want you can keep it, as a reminder, until you have fix the error.

**Comment by cryptoloutre** [comment]
You're welcome. I keep it and I will ping you once fixed ;)

**Comment by irzinfante** [comment]
Hello @cryptoloutre. Take a look at PR #7 please. This worked for me and it may solve the issue.

**Comment by cryptoloutre** [comment]
@irzinfante merged! Thanks a lot and sorry for the inconvenience :/
